### ISSUE TITLE
This extension doesn't seem to work for me on GNOME 46

### ISSUE THREAD

**Issue by jtherrmann** [mipmip/gnome-shell-extensions-highlight-focus#20]
I'm on GNOME 46 / Wayland / Ubuntu 24.04 LTS. This extension doesn't seem to work for me. I assume that when I press the keyboard shortcut `<Super>l`, I should see the temporary border appear. But nothing happens. Am I misunderstanding how this extension works?

**Comment by mipmip** [comment]
I can't reproduce this. Is this still a problem?

**Comment by mipmip** [comment]
This is caused by a shortcut conflict. Have a look at this issue #21 and this discussion topi https://github.com/mipmip/gnome-shell-extensions-highlight-focus/discussions/23
