### ISSUE TITLE
Aesthetics needed

### ISSUE THREAD

**Issue by 3ibod** [mipmip/gnome-shell-extensions-highlight-focus#3]
It's great that there is such an extension, it's not only useful when working with keyboard navigation as you described, but also when working with Blender and Maya 3D windows, for example, it's useful to know that a window has focus in order to use a shortcut for it.
It's cool that when you close the window, the frame goes
 automatically to the new active window. Will there be further support for this extension?
I would like to be able to:
 Adjust the rounding radius to the corners of my windows
 frame color
 Transparency
 Extinction Delay
 Frame thickness and offset relative to the pivot
 And maybe a fade effect for smooth display?
[Screencast from 09-17-2022 09:08:12 AM.webm](https://user-images.githubusercontent.com/58691873/190841626-14a45939-4e07-43ea-b52c-c8158a6726e0.webm)
![Screenshot from 2022-09-17 09-15-38](https://user-images.githubusercontent.com/58691873/190841671-fbc93cc1-b16a-4131-817d-17fb75c03f9a.png)

**Comment by 3ibod** [comment]
Wow, it seems that I could do some of the settings myself
![Screenshot from 2022-09-17 09-37-33](https://user-images.githubusercontent.com/58691873/190842286-f77a0277-9bc6-48ff-b19c-37a6a2917c14.png)

**Comment by mipmip** [comment]
Your welcome to submit a PR.

**Comment by mipmip** [comment]
> Will there be further support for this extension?

Yes there will. And contributions are welcome too. Don't hesitate to submit a PR if you made a useful improvement. Try to fix one issue in a time.

> I would like to be able to: Adjust the rounding radius to the corners of my windows frame color Transparency Extinction Delay Frame thickness and offset relative to the pivot And maybe a fade effect for smooth display?

You have good idea's. Please submit separate issues.

**Comment by mipmip** [comment]
subscribe to #4 #5 #6
